from __future__ import annotations

UPI_MERCHANT_HINTS = {
    "swiggy",
    "zomato",
    "netflix",
    "spotify",
    "myntra",
    "flipkart",
    "amazon",
    "amazonpay",
    "uber",
    "ola",
    "airtel",
    "jio",
    "bigbasket",
    "dmart",
    "pvr",
    "irctc",
    "paytm",
    "phonepe",
    "gpay",
    "aws",
    "gcp",
    "azure",
    "notion",
    "slack",
    "atlassian",
    "zoho",
    "tally",
    "hostinger",
    "godaddy",
}

SIMPLE_MERCHANTS = {
    "swiggy",
    "zomato",
    "netflix",
    "spotify",
    "google",
    "amazon",
    "flipkart",
    "uber",
    "ola",
    "airtel",
    "jio",
    "zoom",
    "slack",
    "notion",
}

UPI_FAST_PATH_MERCHANTS = {
    "swiggy",
    "zomato",
    "uber",
    "ola",
    "amazon",
    "amazonpay",
    "flipkart",
    "myntra",
    "netflix",
    "spotify",
    "airtel",
    "jio",
    "paytm",
    "phonepe",
}

# ── Business keywords ─────────────────────────────────────────────────
# Aligned with taxonomy categories: professional_services, electronics_technology,
# subscriptions_memberships, fees_charges, taxes_government, bills (business)
SLM_BUSINESS_KEYWORDS = {
    # Cloud / SaaS / tech infra (electronics_technology + subscriptions)
    "aws",
    "gcp",
    "azure",
    "cloud",
    "hosting",
    "domain",
    "godaddy",
    "hostinger",
    "digitalocean",
    "server",
    "saas",
    # Productivity / SaaS subscriptions
    "zoom",
    "slack",
    "notion",
    "jira",
    "atlassian",
    "confluence",
    "github",
    "figma",
    "openai",
    "canva",
    "hubspot",
    "salesforce",
    "adobe",
    "creative cloud",
    "google workspace",
    "microsoft",
    "office 365",
    "microsoft 365",
    "zoho",
    "tally",
    "crm",
    # Professional services (professional_services)
    "consulting",
    "consultant",
    "retainer",
    "professional fee",
    "legal",
    "lawyer",
    "advocate",
    "ca fees",
    "chartered accountant",
    "accounting",
    "auditing",
    "audit",
    "bookkeeping",
    # Finance / tax / government (fees_charges, taxes_government)
    "gst",
    "gstin",
    "invoice",
    "tds",
    "tax payment",
    # Business operations
    "software",
    "license",
    "subscription",
    "renewal",
    "annual",
    "agency",
    "marketing",
    "digital marketing",
    "business",
    "workspace",
    "enterprise",
    "team plan",
    "pro license",
}

# ── Personal keywords ─────────────────────────────────────────────────
# Aligned with taxonomy categories: food_dining, groceries, shopping,
# entertainment, health, education, insurance, charity, personal_care, etc.
SLM_PERSONAL_KEYWORDS = {
    # Food & dining (food_dining)
    "swiggy",
    "zomato",
    "restaurant",
    "cafe",
    "dining",
    "dinner",
    "lunch",
    "food order",
    "starbucks",
    "dominos",
    "pizza",
    "mcdonalds",
    "kfc",
    # Groceries (groceries)
    "grocery",
    "groceries",
    "bigbasket",
    "blinkit",
    "zepto",
    "dmart",
    "supermarket",
    "provisions",
    # Shopping / fashion (shopping)
    "myntra",
    "flipkart",
    "shopping",
    "clothes",
    "fashion",
    "ajio",
    "nykaa",
    # Entertainment (entertainment)
    "movie",
    "cinema",
    "pvr",
    "inox",
    "bookmyshow",
    "concert",
    "game",
    # Travel / transport (travel, transport)
    "ola",
    "uber",
    "irctc",
    "hotel",
    "flight",
    "vacation",
    "booking",
    "travel",
    "makemytrip",
    "oyo",
    "cab",
    "taxi",
    "ride fare",
    # Health (health)
    "medical",
    "pharmacy",
    "hospital",
    "doctor",
    "medicine",
    "apollo",
    "1mg",
    "pharmeasy",
    # Education (education)
    "school",
    "school fee",
    "college",
    "tuition",
    "education",
    # Insurance (insurance)
    "lic",
    "insurance",
    "premium",
    "policy",
    # Personal / home (rent, personal_care, charity)
    "rent",
    "household",
    "personal",
    "family",
    "spouse",
    "salon",
    "gym",
    "donation",
    "temple",
    "church",
    "charity",
    # Fuel (fuel)
    "fuel",
    "petrol",
    "commute",
    # Bills (personal context)
    "electricity bill",
    "water bill",
    "electricity",
    "reimbursement",
    # Streaming (subscriptions — personal)
    "netflix",
    "spotify",
    "prime video",
    "hotstar",
    "youtube premium",
}

SLM_UPI_BUSINESS_HINTS = {
    "aws",
    "gcp",
    "azure",
    "zoho",
    "tally",
    "notion",
    "slack",
    "atlassian",
    "adobe",
    "hubspot",
    "salesforce",
    "consulting",
    "agency",
    "gst",
    "godaddy",
    "hostinger",
    "digitalocean",
    "github",
    "figma",
}

SLM_UPI_PERSONAL_HINTS = {
    "swiggy",
    "zomato",
    "netflix",
    "spotify",
    "myntra",
    "flipkart",
    "uber",
    "ola",
    "dmart",
    "bigbasket",
    "pvr",
    "pharmacy",
    "grocery",
    "lic",
    "irctc",
    "makemytrip",
    "oyo",
    "bookmyshow",
}

LEAK_MERCHANT_TOKENS = {
    "zoom",
    "google",
    "meet",
    "slack",
    "notion",
    "atlassian",
    "aws",
    "netflix",
    "spotify",
}

LEAK_SUBSCRIPTION_MARKERS = {"subscription", "monthly", "license", "plan", "renew"}
LEAK_SAAS_VIDEO = {"zoom", "google", "meet"}
LEAK_SAAS_CHAT = {"slack", "teams"}
LEAK_SAAS_DOCS = {"notion", "confluence"}

TAX_MISCATEGORY_HINTS = {
    "aws",
    "google workspace",
    "software",
    "license",
    "hosting",
    "consulting",
}
