#!/usr/bin/env python3
from __future__ import annotations

import argparse
import socket
from pathlib import Path

DEFAULT_API_PORT = 18000
DEFAULT_POSTGRES_PORT = 15432
API_RANGE_END = 18100
POSTGRES_RANGE_END = 15550


def _is_port_available(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            sock.bind(("127.0.0.1", port))
        except OSError:
            return False
        return True


def _pick_port(preferred: int, range_end: int, reserved: set[int]) -> int:
    if preferred not in reserved and _is_port_available(preferred):
        return preferred
    for port in range(preferred + 1, range_end + 1):
        if port in reserved:
            continue
        if _is_port_available(port):
            return port
    raise RuntimeError(f"No free port found in range {preferred}-{range_end}")


def _read_existing(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def main() -> int:
    parser = argparse.ArgumentParser(description="Allocate conflict-free runtime ports for docker compose")
    parser.add_argument("--output", default=".env.runtime", help="Destination env file")
    args = parser.parse_args()

    output_path = Path(args.output).resolve()
    existing = _read_existing(output_path)

    preferred_api = int(existing.get("HOST_API_PORT", str(DEFAULT_API_PORT)))
    preferred_postgres = int(existing.get("HOST_POSTGRES_PORT", str(DEFAULT_POSTGRES_PORT)))

    api_port = _pick_port(preferred_api, API_RANGE_END, reserved=set())
    postgres_port = _pick_port(preferred_postgres, POSTGRES_RANGE_END, reserved={api_port})

    content = (
        "# Auto-generated by scripts/allocate_runtime_ports.py\n"
        f"HOST_API_PORT={api_port}\n"
        f"HOST_POSTGRES_PORT={postgres_port}\n"
    )
    output_path.write_text(content, encoding="utf-8")

    print(f"Allocated HOST_API_PORT={api_port}")
    print(f"Allocated HOST_POSTGRES_PORT={postgres_port}")
    print(f"Wrote runtime port file: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
